name: Run on Fly
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Run script
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Run pg_dump
        id: pg_dump
        run: |
          PG_DUMP_OUTPUT=$(flyctl ssh console --command "pg_dump ${{ secrets.FLY_DB_URI }}")
          echo $PG_DUMP_OUTPUT
          echo pg_data_dump=$PG_DUMP_OUTPUT >> "$GITHUB_OUTPUT"

      - name: Use the pg_dump output
        run: |
          echo ${{ steps.pg_dump.outputs.pg_data_dump }}

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
